### ISSUE TITLE
Solo buttons in track or mixer section are not working

### ISSUE THREAD

**Issue by goldenhours-71** [FLUX-SE/ReaVolution#1]
Hi,

Perhaps this is not implemented yet, but for some reason the Solo button function does not seem to be working, i.e. it does not prevent ReaVolution from sending ALL tracks to SPAT at all times.

Regards,
David

**Comment by vincentcarlier** [comment]
Hi David,

As far as I know, the solo button in DAWs do not stop the other tracks plugins to process audio, it just cuts their output. For this reason, Spat will always receive audio even if solo is engaged on some tracks. It may be the same flavour with the mute buttons.

If you need to solo, please use the sources solo button directly in Spat.

I hope this helps!

Best,
Vincent
